baseURL = "https://www.404fix.cn/"
languageCode = "en-us"
title = "一文破晓"
theme = "yinyang"
DefaultContentLanguage = "cn"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    style = "catppuccin-latte"
    tabWidth = 2

[taxonomies]
year = "years"
tag = "tags"
category = "categories"

[params]
mainSections = ["posts"]
headTitle = "Wen"
disqus = "Wen"
favicon = "/assets/images/favicon.png"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script><script src="/assets/js/code.js"></script>'
extraCSSFiles = ["/assets/css/code.css"]
[[params.socials]]
name = "About Me"
link = "/posts/about"
[[params.socials]]
name = "Github"
link = "https://github.com/ThinkerWen/"
