name: Deploy 404fix

on:
  push:
    branches:
      - yinyang

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.102.1'

    - name: Build Hugo site
      run: hugo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        PERSONAL_TOKEN: ${{ secrets.GH_PAT }}
        PUBLISH_DIR: ./public
        EXTERNAL_REPOSITORY: ThinkerWen/ThinkerWen.github.io
        PUBLISH_BRANCH: yinyang_deploy
        CNAME: www.404fix.cn
        user_name: 'ThinkerWen'
        user_email: '296854007@qq.com'
        commit_message: ${{ github.event.head_commit.message }}
